{
}
unit FurrySkyrim_Preferences;

interface
implementation
uses FurrySkyrimTools, BDScriptTools, xEditAPI, Classes, SysUtils, StrUtils, Windows;


Procedure SetPreferences;
begin
    SetRace('NordRace', 'LykaiosRace');

    LabelHeadpart('00HairLykaiosMaleDreads001_', 'DREADS');
    LabelHeadpart('00HairLykaiosMaleDreads001_', 'BOLD');
    LabelHeadpart('00HairLykaiosMaleDreads001_', 'FUNKY');
    // LabelHeadpart('00HairLykaiosMaleDreads002_', 'DREADS'); // Dark version
    LabelHeadpart('00HairLykaiosMaleDreads003_', 'DREADS');
    LabelHeadpart('00HairLykaiosMaleDreads003_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleDreads003_', 'BOLD');
    LabelHeadpart('00HairLykaiosMaleDreads003_', 'FUNKY');
    // LabelHeadpart('00HairLykaiosMaleDreads004_', 'DREADS'); // Dark version
    LabelHeadpart('00HairLykaiosMaleDreadsFringe_', 'DREADS');
    LabelHeadpart('00HairLykaiosMaleDreadsFringe_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleDreadsFringe_', 'BOLD');
    LabelHeadpart('00HairLykaiosMaleDreadsFringe_', 'FUNKY');
    LabelHeadpart('00HairLykaiosMaleDreadsFringe_', 'YOUNG');
    LabelHeadpart('00HairLykaiosMaleDreadsHeadband_', 'DREADS');
    LabelHeadpart('00HairLykaiosMaleDreadsHeadband_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleDreadsHeadband_', 'BOLD');
    LabelHeadpart('00HairLykaiosMaleDreadsHeadband_', 'FUNKY');
    LabelHeadpart('00HairLykaiosMaleDreadsHeadband_', 'FEATHERS');
    LabelHeadpart('00HairLykaiosMaleFringeFlip001_', 'YOUNG');
    LabelHeadpart('00HairLykaiosMaleFringeFlip001_', 'SHORT');
    LabelHeadpart('00HairLykaiosMaleLionMane001', 'MANE');
    LabelHeadpart('00HairLykaiosMaleLionMane001', 'LONG');
    LabelHeadpart('00HairLykaiosMaleLionMane002', 'MANE');
    LabelHeadpart('00HairLykaiosMaleLionMane002', 'LONG');
    LabelHeadpart('00HairLykaiosMaleLionMane002', 'YOUNG');
    LabelHeadpart('00HairLykaiosMaleLionManeFringeLeftBraid_', 'MANE');
    LabelHeadpart('00HairLykaiosMaleLionManeFringeLeftBraid_', 'LONG');
    LabelHeadpart('00HairLykaiosMaleLionManeFringeLeftBraid_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleLionManeFringeLeftBraid_', 'BRAIDS');
    LabelHeadpart('00HairLykaiosMaleLionManeHeadband', 'MANE');
    LabelHeadpart('00HairLykaiosMaleLionManeHeadband', 'LONG');
    LabelHeadpart('00HairLykaiosMaleLionManeHeadband', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleLionManeHeadband', 'FEATHERS');
    LabelHeadpart('00HairLykaiosMaleLionManebraids', 'MANE');
    LabelHeadpart('00HairLykaiosMaleLionManebraids', 'LONG');
    LabelHeadpart('00HairLykaiosMaleLionManebraids', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleLionManebraids', 'BRAIDS');
    LabelHeadpart('00HairLykaiosMaleLongBraid001_', 'BRAIDS');
    LabelHeadpart('00HairLykaiosMaleLongBraid001_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleLongBraid001_', 'TIEDBACK');
    LabelHeadpart('00HairLykaiosMaleLongBraid001_', 'BRAIDS');
    LabelHeadpart('00HairLykaiosMaleLongBraid002_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleLongBraid002_', 'TIEDBACK');
    LabelHeadpart('00HairLykaiosMaleLongBraid002_', 'BRAIDS');
    LabelHeadpart('00HairLykaiosMaleLongBraid002_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleLongBraidLeft_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleLongBraidLeft_', 'TIEDBACK');
    LabelHeadpart('00HairLykaiosMaleLongBraidLeft_', 'BRAIDS');
    LabelHeadpart('00HairLykaiosMaleLongBraidLeft_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleMohawk001_', 'MOHAWK');
    LabelHeadpart('00HairLykaiosMaleMohawk001_', 'BRAIDS');
    LabelHeadpart('00HairLykaiosMaleMohawk001_', 'MILITARY');
    LabelHeadpart('00HairLykaiosMaleMohawk001_', 'BOLD');
    LabelHeadpart('00HairLykaiosMaleMohawk003_', 'MOHAWK');
    LabelHeadpart('00HairLykaiosMaleMohawk003_', 'FEATHERS');
    LabelHeadpart('00HairLykaiosMaleMohawk003_', 'BOLD');
    LabelHeadpart('00HairLykaiosMaleMohawkFringe_', 'MOHAWK');
    LabelHeadpart('00HairLykaiosMaleMohawkFringe_', 'YOUNG');
    LabelHeadpart('00HairLykaiosMaleMohawkFringe_', 'BOLD');
    LabelHeadpart('00HairLykaiosMaleShaggyHair002_', 'LONG');
    LabelHeadpart('00HairLykaiosMaleShaggyHair002_', 'MESSY');
    LabelHeadpart('00HairLykaiosMaleShaggyHair003_', 'LONG');
    LabelHeadpart('00HairLykaiosMaleShaggyHair003_', 'MESSY');
    LabelHeadpart('00HairLykaiosMaleShaggyHair003_', 'FEATHERS');
    LabelHeadpart('00HairLykaiosMaleShorCrop001_', 'SHORT');
    LabelHeadpart('00HairLykaiosMaleShorCrop001_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleShorCrop001_', 'MILITARY');
    LabelHeadpart('00HairLykaiosMaleShorCrop002_', 'SHORT');
    LabelHeadpart('00HairLykaiosMaleShorCrop002_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleShorCrop002_', 'YOUNG');
    LabelHeadpart('00HairLykaiosMaleShorCrop003_', 'SHORT');
    LabelHeadpart('00HairLykaiosMaleShorCrop003_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleShorCrop003_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleShorCrop004_', 'SHORT');
    LabelHeadpart('00HairLykaiosMaleShorCrop004_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleShorCrop004_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleShorCrop004_', 'FEATHERS');
    LabelHeadpart('00HairLykaiosMaleTiedStyle001_', 'LONG');
    LabelHeadpart('00HairLykaiosMaleTiedStyle001_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleTiedStyle001_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleTiedStyleFringe_', 'LONG');
    LabelHeadpart('00HairLykaiosMaleTiedStyleFringe_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleTiedStyleFringe_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleTiedStyleFringe_', 'YOUNG');
    LabelHeadpart('00HairLykaiosMaleTiedStyleHeadband_', 'LONG');
    LabelHeadpart('00HairLykaiosMaleTiedStyleHeadband_', 'NOBLE');
    LabelHeadpart('00HairLykaiosMaleTiedStyleHeadband_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleTiedStyleHeadband_', 'YOUNG');
    LabelHeadpart('00HairLykaiosMaleTiedStyleHeadband_', 'FEATHERS');
    LabelHeadpart('00HairLykaiosMaleVanillaBraid001_', 'LONG');
    LabelHeadpart('00HairLykaiosMaleVanillaBraid001_', 'NEAT');
    LabelHeadpart('00HairLykaiosMaleVanillaBraid001_', 'TIEDBACK');
    LabelHeadpart('00HairLykaiosMaleVanillaCrop001_', 'SHORT');
    LabelHeadpart('00HairLykaiosMaleVanillaCrop001_', 'YOUNG');
    LabelHeadpart('00HairLykaiosMaleVanillaCrop001_', 'MILITARY');
    LabelHeadpart('00HairLykaiosMaleVanillaHair001_', 'MESSY');
    LabelHeadpart('00HairLykaiosMaleVanillaHair001_', 'LONG');
    LabelHeadpart('HairBeastSidehawk', 'MOHAWK');
    LabelHeadpart('HairBeastSidehawk', 'FUNKY');
    LabelHeadpart('HairBeastSidehawk', 'BOLD');

    // AssignHeadpart('HairMaleNord01', '00HairLykaiosMaleVanillaHair001_');
    // AssignHeadpart('HairMaleNord02', '00HairLykaiosMaleDreads001_');
    // AssignHeadpart('HairMaleNord02', '00HairLykaiosMaleDreads002_');
    // AssignHeadpart('HairMaleNord02', '00HairLykaiosMaleDreads003_');
    // AssignHeadpart('HairMaleNord02', '00HairLykaiosMaleDreads004_');
    // AssignHeadpart('HairMaleNord03', '00HairLykaiosMaleTiedStyle001_');
    // AssignHeadpart('HairMaleNord03', '00HairLykaiosMaleLionMane001');
    // AssignHeadpart('HairMaleNord03', '00HairLykaiosMaleLionMane002');
    // AssignHeadpart('HairMaleNord04', '00HairLykaiosMaleLionManeFringeLeftBraid_');
    // AssignHeadpart('HairMaleNord04', '00HairLykaiosMaleLionManeHeadband');
    // AssignHeadpart('HairMaleNord04', '00HairLykaiosMaleLionManeBraids');
    // AssignHeadpart('HairMaleNord05', '00HairLykaiosMaleDreads001_');
    // AssignHeadpart('HairMaleNord05', '00HairLykaiosMaleDreads002_');
    // AssignHeadpart('HairMaleNord06', '00HairLykaiosMaleDreads003_');
    // AssignHeadpart('HairMaleNord06', '00HairLykaiosMaleDreads004_');
    // AssignHeadpart('HairMaleNord06', '00HairLykaiosMaleDreadsHeadband_');
    // AssignHeadpart('HairMaleNord06', '00HairLykaiosMaleLionManeFringeLeftBraid_');
    // AssignHeadpart('HairMaleNord06', '00HairLykaiosMaleLionManeBraids');
    // AssignHeadpart('HairMaleNord06', '00HairLykaiosMaleTiedStyle001_');
    // AssignHeadpart('HairMaleNord06', '00HairLykaiosMaleTiedStyleFringe_');
    // AssignHeadpart('HairMaleNord06', '00HairLykaiosMaleTiedStyleHeadband_');
    // AssignHeadpart('HairMaleNord07', '00HairLykaiosMaleLongBraid001_');
    // AssignHeadpart('HairMaleNord07', '00HairLykaiosMaleShorCrop001_');
    // AssignHeadpart('HairMaleNord07', '00HairLykaiosMaleShorCrop002_');
    // AssignHeadpart('HairMaleNord07', '00HairLykaiosMaleVanillaCrop001_');
    // AssignHeadpart('HairMaleNord08', '00HairLykaiosMaleShorCrop003_');
    // AssignHeadpart('HairMaleNord09', '00HairLykaiosMaleShorCrop003_');
    // AssignHeadpart('HairMaleNord09', '00HairLykaiosMaleDreds001_');
    // AssignHeadpart('HairMaleNord09', '00HairLykaiosMaleDreds002_');
    // AssignHeadpart('HairMaleNord09', '00HairLykaiosMaleShorCrop004_');
    // AssignHeadpart('HairMaleNord09', '00HairLykaiosMaleVanillaCrop001_');
    // AssignHeadpart('HairMaleNord10', '00HairLykaiosMaleLongBraid001_');
    // AssignHeadpart('HairMaleNord10', '00HairLykaiosMaleBeastSidehawk');
    // AssignHeadpart('HairMaleNord10', '00HairLykaiosMaleVanillaBraid001_');
    // AssignHeadpart('HairMaleNord10', '00HairLykaiosMaleShorCrop003_');
    // AssignHeadpart('HairMaleNord10', '00HairLykaiosMaleShorCrop004_');
    // AssignHeadpart('HairMaleNord11', '00HairLykaiosMaleShorCrop003_');
    // AssignHeadpart('HairMaleNord11', '00HairLykaiosMaleShorCrop004_');
    // AssignHeadpart('HairMaleNord11', '00HairLykaiosMaleFringeFlip001_');
    // AssignHeadpart('HairMaleNord11', '00HairLykaiosMaleDreadsHeadband_');
    // AssignHeadpart('HairMaleNord12', '00HairLykaiosMaleVanillaBraid001_');
    // AssignHeadpart('HairMaleNord13', '00HairLykaiosMaleTiedStyle001_');
    // AssignHeadpart('HairMaleNord13', '00HairLykaiosMaleTiedStyle002_');
    // AssignHeadpart('HairMaleNord14', '00HairLykaiosMaleShorCrop001_');
    // AssignHeadpart('HairMaleNord14', '00HairLykaiosMaleShorCrop002_');
    // AssignHeadpart('HairMaleNord14', '00HairLykaiosMaleShorCrop004_');
    // AssignHeadpart('HairMaleNord15', '00HairLykaiosMaleShorCrop001_');
    // AssignHeadpart('HairMaleNord15', '00HairLykaiosMaleShorCrop002_');
    // AssignHeadpart('HairMaleNord15', '00HairLykaiosMaleShorCrop004_');
    // AssignHeadpart('HairMaleNord16', '00HairLykaiosMaleMohawk001_');
    // AssignHeadpart('HairMaleNord16', '00HairLykaiosMaleMohawk002_');
    // AssignHeadpart('HairMaleNord16', '00HairLykaiosMaleMohawk003_');
    // AssignHeadpart('HairMaleNord16', '00HairLykaiosMaleMohawkFringe_');
    // AssignHeadpart('HairMaleNord17', '00HairLykaiosMaleMohawk001_');
    // AssignHeadpart('HairMaleNord17', '00HairLykaiosMaleMohawk002_');
    // AssignHeadpart('HairMaleNord17', '00HairLykaiosMaleMohawk003_');
    // AssignHeadpart('HairMaleNord17', '00HairLykaiosMaleMohawkFringe_');
    // AssignHeadpart('HairMaleNord18', '00HairLykaiosMaleShaggyHair001_');
    // AssignHeadpart('HairMaleNord18', '00HairLykaiosMaleShaggyHair002_');
    // AssignHeadpart('HairMaleNord18', '00HairLykaiosMaleShaggyHair003_');
    // AssignHeadpart('HairMaleNord19', '00HairLykaiosMaleShaggyHair001_');
    // AssignHeadpart('HairMaleNord19', '00HairLykaiosMaleShaggyHair002_');
    // AssignHeadpart('HairMaleNord19', '00HairLykaiosMaleShaggyHair003_');
    // AssignHeadpart('HairMaleNord20', '00HairLykaiosMaleBeastSidehawk');

    // AssignHeadpart('HairMaleElder5', '00HairLykaiosMaleDreads001_');

    AssignHeadpart('MaleEyesHumanAmber', '00LykaiosMaleEyesAmber');
    AssignHeadpart('MaleEyesHumanAmberBlindRight', '00LykaiosMaleEyesAlbino');
    AssignHeadpart('MaleEyesHumanBlind', '00LykaiosMaleEyesAlbino');
    AssignHeadpart('MaleEyesHumanBrightGreen', '00LykaiosMaleEyesGreen');
    AssignHeadpart('MaleEyesHumanBrightGreenBlindRight', '00LykaiosMaleEyesGreen');
    AssignHeadpart('MaleEyesHumanBrown', '00LykaiosMaleEyesBrown');
    AssignHeadpart('MaleEyesHumanBrownBlindLeft', '00LykaiosMaleEyesAlbino');
    AssignHeadpart('MaleEyesHumanBrownBlindRight', '00LykaiosMaleEyesAlbino');
    AssignHeadpart('MaleEyesHumanBrownBloodShot', '00LykaiosMaleEyesBrown');
    AssignHeadpart('MaleEyesHumanDarkBlue', '00LykaiosMaleEyesDarkBlue');
    AssignHeadpart('MaleEyesHumanDemon', '00LykaiosMaleEyesRed');
    AssignHeadpart('MaleEyesHumanGreenHazelLeft', '00LykaiosMaleEyesYellow');
    AssignHeadpart('MaleEyesHumanGrey', '00LykaiosMaleEyesBase');
    AssignHeadpart('MaleEyesHumanHazel', '00LykaiosMaleEyesYellow');
    AssignHeadpart('MaleEyesHumanHazelBrown', '00LykaiosMaleEyesYellow');
    AssignHeadpart('MaleEyesHumanIceBlue', '00LykaiosMaleEyesBlue');
    AssignHeadpart('MaleEyesHumanLeftBlindSingle', '00LykaiosMaleEyesAlbino');
    AssignHeadpart('MaleEyesHumanLightBlue', '00LykaiosMaleEyesSnow1');
    AssignHeadpart('MaleEyesHumanLightBlueBlindLeft', '00LykaiosMaleEyesAlbino');
    AssignHeadpart('MaleEyesHumanLightBlueBloodShot', '00LykaiosMaleEyesSnow1');
    AssignHeadpart('MaleEyesHumanLightGrey', '00LykaiosMaleEyesGrey');
    AssignHeadpart('MaleEyesHumanLightIceGreyBlindLeft', '00LykaiosMaleEyesLilac');
    AssignHeadpart('MaleEyesHumanRightBlindSingle', '00LykaiosMaleEyesAlbino');
    AssignHeadpart('MaleEyesHumanRightHazleBrownRight', '00LykaiosMaleEyesBrown');
    AssignHeadpart('MaleEyesHumanVampire', '00LykaiosMaleEyesVampire');


    // Vanilla equivalents

    // Khajiit hair
    // AssignHeadpart('HairMaleNord01', 'HairKhajiitMale02');
    // AssignHeadpart('HairMaleNord02', 'HairKhajiitMale01');
    // AssignHeadpart('HairMaleNord02', 'HairKhajiitMale04');
    // AssignHeadpart('HairMaleNord03', 'HairKhajiitMale05');
    // AssignHeadpart('HairMaleNord04', 'HairKhajiitMale04');
    // AssignHeadpart('HairMaleNord04', 'HairKhajiitMale09');
    // AssignHeadpart('HairMaleNord05', 'HairKhajiitMale02');
    // AssignHeadpart('HairMaleNord05', 'HairKhajiitMale03');
    // AssignHeadpart('HairMaleNord06', 'HairKhajiitMale05');
    // AssignHeadpart('HairMaleNord07', 'HairKhajiitMale02');
    // AssignHeadpart('HairMaleNord07', 'HairKhajiitMale03');
    // AssignHeadpart('HairMaleNord08', 'HairKhajiitMale04');
    // AssignHeadpart('HairMaleNord08', 'HairKhajiitMale09');
    // AssignHeadpart('HairMaleNord08', 'HairKhajiitMale10');
    // AssignHeadpart('HairMaleNord09', 'HairKhajiitMale06');
    // AssignHeadpart('HairMaleNord10', 'HairKhajiitMale09');
    // AssignHeadpart('HairMaleNord11', 'HairKhajiitMale06');
    // AssignHeadpart('HairMaleNord11', 'HairKhajiitMale01');
    // AssignHeadpart('HairMaleNord12', 'HairKhajiitMale06');
    // AssignHeadpart('HairMaleNord13', 'HairKhajiitMale06');
    // AssignHeadpart('HairMaleNord14', 'HairKhajiitMale03');
    // AssignHeadpart('HairMaleNord14', 'HairKhajiitMale06');
    // AssignHeadpart('HairMaleNord15', 'HairKhajiitMale03');
    // AssignHeadpart('HairMaleNord15', 'HairKhajiitMale06');
    // AssignHeadpart('HairMaleNord16', 'HairKhajiitMale07');
    // AssignHeadpart('HairMaleNord17', 'HairKhajiitMale07');
    // AssignHeadpart('HairMaleNord18', 'HairKhajiitMale08');
    // AssignHeadpart('HairMaleNord19', 'HairKhajiitMale08');
    // AssignHeadpart('HairMaleNord20', 'HairKhajiitMale09');
    
    // Khajiit eyes
    // AssignHeadpart('MaleEyesHumanAmber', 'MaleEyesKhajiitBase');
    // AssignHeadpart('MaleEyesHumanAmberBlindRight', '');
    // AssignHeadpart('MaleEyesHumanBlind', 'MaleEyesKhajiitBlind');
    // AssignHeadpart('MaleEyesHumanBrightGreen', 'MaleEyesKhajiitOrange');
    // AssignHeadpart('MaleEyesHumanBrightGreenBlindRight', 'MaleEyesKhajiitOrangeNarrow');
    // AssignHeadpart('MaleEyesHumanBrown', 'MaleEyesKhajiitBase');
    // AssignHeadpart('MaleEyesHumanBrownBlindLeft', 'MaleEyesKhajiitBaseNarrow');
    // AssignHeadpart('MaleEyesHumanBrownBlindRight', 'MaleEyesKhajiitBaseNarrow');
    // AssignHeadpart('MaleEyesHumanBrownBloodShot', 'MaleEyesKhajiitBase');
    // AssignHeadpart('MaleEyesHumanDarkBlue', 'MaleEyesKhajiitBlue');
    // AssignHeadpart('MaleEyesHumanDemon', 'MaleEyesKhajiitYellowNarrow');
    // AssignHeadpart('MaleEyesHumanGreenHazelLeft', 'MaleEyesKhajiitOrangeNarrow');
    // AssignHeadpart('MaleEyesHumanGrey', 'MaleEyesKhajiitYellow');
    // AssignHeadpart('MaleEyesHumanHazel', 'MaleEyesKhajiitOrange');
    // AssignHeadpart('MaleEyesHumanHazelBrown', 'MaleEyesKhajiitOrangeNarrow');
    // AssignHeadpart('MaleEyesHumanIceBlue', 'MaleEyesKhajiitIce');
    // AssignHeadpart('MaleEyesHumanLeftBlindSingle', 'MaleEyesKhajiitBaseNarrow');
    // AssignHeadpart('MaleEyesHumanLightBlue', 'MaleEyesKhajiitIceNarrow');
    // AssignHeadpart('MaleEyesHumanLightBlueBlindLeft', 'MaleEyesKhajiitIceNarrow');
    // AssignHeadpart('MaleEyesHumanLightBlueBloodShot', 'MaleEyesKhajiitIceNarrow');
    // AssignHeadpart('MaleEyesHumanLightGrey', 'MaleEyesKhajiitIce');
    // AssignHeadpart('MaleEyesHumanLightIceGreyBlindLeft', 'MaleEyesKhajiitIceNarrow');
    // AssignHeadpart('MaleEyesHumanRightBlindSingle', 'MaleEyesKhajiitYellowNarrow');
    // AssignHeadpart('MaleEyesHumanRightHazleBrownRight', 'MaleEyesKhajiitBaseNarrow');
    // AssignHeadpart('MaleEyesHumanVampire', 'MaleEyesKhajiitVampire');

    // Vanilla NPC equivalents
    NPCEquivalent('AstridEnd', 'Astrid');

    LabelVanillaHeadparts;
end;

procedure LabelVanillaHeadparts;
begin
    LabelHeadpart('HairMaleNord01', 'MESSY');
    LabelHeadpart('HairMaleNord01', 'LONG');
    LabelHeadpart('HairMaleNord02', 'MESSY');
    LabelHeadpart('HairMaleNord02', 'LONG');
    LabelHeadpart('HairMaleNord02', 'BRAIDS');
    LabelHeadpart('HairMaleNord03', 'NOBLE');
    LabelHeadpart('HairMaleNord03', 'LONG');
    LabelHeadpart('HairMaleNord03', 'BRAIDS');
    LabelHeadpart('HairMaleNord04', 'MESSY');
    LabelHeadpart('HairMaleNord04', 'LONG');
    LabelHeadpart('HairMaleNord04', 'BRAIDS');
    LabelHeadpart('HairMaleNord05', 'NEAT');
    LabelHeadpart('HairMaleNord05', 'LONG');
    LabelHeadpart('HairMaleNord05', 'TIEDBACK');
    LabelHeadpart('HairMaleNord06', 'BOLD');
    LabelHeadpart('HairMaleNord06', 'BRAIDS');
    LabelHeadpart('HairMaleNord07', 'SHORT');
    LabelHeadpart('HairMaleNord07', 'NEAT');
    LabelHeadpart('HairMaleNord08', 'FUNKY');
    LabelHeadpart('HairMaleNord08', 'BRAIDS');
    LabelHeadpart('HairMaleNord08', 'SHORT');
    LabelHeadpart('HairMaleNord09', 'NEAT');
    LabelHeadpart('HairMaleNord09', 'SHORT');
    LabelHeadpart('HairMaleNord09', 'MILITARY');
    LabelHeadpart('HairMaleNord10', 'NEAT');
    LabelHeadpart('HairMaleNord10', 'SHORT');
    LabelHeadpart('HairMaleNord10', 'BRAIDS');
    LabelHeadpart('HairMaleNord11', 'NEAT');
    LabelHeadpart('HairMaleNord11', 'SHORT');
    LabelHeadpart('HairMaleNord11', 'TIEDBACK');
    LabelHeadpart('HairMaleNord11', 'BRAIDS');
    LabelHeadpart('HairMaleNord12', 'NEAT');
    LabelHeadpart('HairMaleNord12', 'LONG');
    LabelHeadpart('HairMaleNord12', 'TIEDBACK');
    LabelHeadpart('HairMaleNord13', 'LONG');
    LabelHeadpart('HairMaleNord13', 'BOLD');
    LabelHeadpart('HairMaleNord13', 'YOUNG');
    LabelHeadpart('HairMaleNord13', 'TIEDBACK');
    LabelHeadpart('HairMaleNord14', 'SHORT');
    LabelHeadpart('HairMaleNord14', 'NEAT');
    LabelHeadpart('HairMaleNord14', 'MILITARY');
    LabelHeadpart('HairMaleNord15', 'SHORT');
    LabelHeadpart('HairMaleNord15', 'MESSY');
    LabelHeadpart('HairMaleNord16', 'MOHAWK');
    LabelHeadpart('HairMaleNord16', 'BRAIDS');
    LabelHeadpart('HairMaleNord16', 'BOLD');
    LabelHeadpart('HairMaleNord16', 'FUNKY');
    LabelHeadpart('HairMaleNord17', 'MOHAWK');
    LabelHeadpart('HairMaleNord17', 'BOLD');
    LabelHeadpart('HairMaleNord17', 'BRAIDS');
    LabelHeadpart('HairMaleNord17', 'FUNKY');
    LabelHeadpart('HairMaleNord18', 'LONG');
    LabelHeadpart('HairMaleNord18', 'MESSY');
    LabelHeadpart('HairMaleNord19', 'LONG');
    LabelHeadpart('HairMaleNord19', 'MESSY');
    LabelHeadpart('HairMaleNord19', 'MATURE');
    LabelHeadpart('HairMaleNord20', 'MOHAWK');
    LabelHeadpart('HairMaleNord20', 'LONG');
    LabelHeadpart('HairMaleNord20', 'BOLD');
    LabelHeadpart('HairMaleNord20', 'FUNKY');



end;

end.