{ Auto-generated by Python — for use in xEdit }
unit userscript;

var
  headPart: IInterface;
  targetFile: IInterface;

// Returns a newly created main record of the given signature in aFile.
// Uses only stock xEdit routines: GroupBySignature and Add.
function AddNewRecord(aFile: IInterface; sig: string): IInterface;
var
  grp: IInterface;
begin
  Result := nil;
  if not Assigned(aFile) or (Length(sig) <> 4) then
    Exit;

  // Get or create the target group inside the file
  grp := GroupBySignature(aFile, sig);
  if not Assigned(grp) then
    grp := Add(aFile, sig, True); // creates the group if missing

  if not Assigned(grp) then
    Exit;

  // Add the new record to the group and return it
  Result := Add(grp, sig, True);
end;

function Initialize: integer;
var e: IInterface;
begin
  targetFile := FileByName('YASCanineRaces.esp');
  if not Assigned(targetFile) then
  begin
    targetFile := FileByName('YASCanineRaces.esm');
  end;
  if not Assigned(targetFile) then
  begin
    AddMessage('Target plugin not found');
    Result := 1;
    exit;
  end;

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemEarrings01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemEarrings01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemEarrings01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemEarrings01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemEarrings01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemEarrings01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings01_XebaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemEarrings02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemEarrings02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemEarrings02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemEarrings02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemEarrings02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemEarrings02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings02_XebaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemEarrings03');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemEarrings03');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemEarrings03');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemEarrings03');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemEarrings03');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemEarrings03');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings03_XebaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemEarrings04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemEarrings04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemEarrings04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemEarrings04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemEarrings04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemEarrings04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings04_XebaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemEarrings05');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemEarrings05');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemEarrings05');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemEarrings05');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemEarrings05');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemEarrings05');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings05_XebaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemEarrings06');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemEarrings06');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemEarrings06');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemEarrings06');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemEarrings06');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemEarrings06');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings06_XebaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemEarrings07');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemEarrings07');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemEarrings07');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemEarrings07');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemEarrings07');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemEarrings07');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings07_XebaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemEarrings08');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemEarrings08');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemEarrings08');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemEarrings08');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemEarrings08');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemEarrings08');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemEarrings08_XebaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemFeatherL');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemFeatherL');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemFeatherL');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemFeatherL');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemFeatherL');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemFeatherL');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherL_XebaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKettuFemFeatherR');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Kettu.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Kettu.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_KettuChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKonoiFemFeatherR');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Konoi.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Konoi.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_KonoiChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKygarraFemFeatherR');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Kygarra.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Kygarra.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_KygarraChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLykaiosFemFeatherR');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Lykaios.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Lykaios.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_LykaiosChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASVaalsarkFemFeatherR');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Vaalsark.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Vaalsark.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_VaalsarkChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASXebaFemFeatherR');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Xeba.nif');
  Add(headpart, 'Parts', True);
  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_Xeba.tri');
  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Dog/Earrings/Fem/DogFemFeatherR_XebaChargen.tri');

end;

end.
