
//  For use in xEdit. Auto-generated by BDGenerateHeadpartScript.py on 2025-12-30 09:11:14.131484.
unit userscript;
var
  headPart: IInterface;
  targetFile: IInterface;

// Returns a newly created main record of the given signature in aFile.
// Uses only stock xEdit routines: GroupBySignature and Add.
function AddNewRecord(aFile: IInterface; sig: string): IInterface;
var
  grp: IInterface;
begin
  Result := nil;
  if not Assigned(aFile) or (Length(sig) <> 4) then
    Exit;

  // Get or create the target group inside the file
  grp := GroupBySignature(aFile, sig);
  if not Assigned(grp) then
    grp := Add(aFile, sig, True); // creates the group if missing

  if not Assigned(grp) then
    Exit;

  // Add the new record to the group and return it
  Result := Add(grp, sig, True);
end;

function Initialize: integer;
var e: IInterface;
begin
  targetFile := FileByName('BDCatRaces.esp');
  if not Assigned(targetFile) then
  begin
    targetFile := FileByName('BDCatRaces.esm');
  end;
  if not Assigned(targetFile) then
  begin
    AddMessage('Target plugin not found');
    Result := 1;
    exit;
  end;

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsB01020304');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsB01020304');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsB01020304');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsB01020304');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01020304_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsB01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsB01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsB01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsB01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB01_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsB02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsB02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsB02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsB02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB02_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsB04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsB04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsB04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsB04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsB04_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsBTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsBTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsBTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsBTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsBTalon_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsL01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsL01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsL01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsL01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL01_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsL02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsL02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsL02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsL02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL02_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsL04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsL04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsL04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsL04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsL04_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsLFeather');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsLFeather');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsLFeather');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsLFeather');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLFeather_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsLTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsLTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsLTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsLTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsLTalon_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsR01020304');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsR01020304');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsR01020304');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsR01020304');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01020304_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsR01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsR01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsR01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsR01');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR01_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsR02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsR02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsR02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsR02');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR02_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsR04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsR04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsR04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsR04');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsR04_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsRFeather');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsRFeather');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsRFeather');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsRFeather');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRFeather_TigerChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASDumaMaleEarringsRTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_Duma.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_Duma.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_DumaChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASKaloMaleEarringsRTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_Kalo.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_Kalo.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_KaloChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASLionMaleEarringsRTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_Lion.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_Lion.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_LionChargen.tri');

  headPart := AddNewRecord(targetFile, 'HDPT');
  SetElementEditValues(headPart, 'EDID', 'YASTigerMaleEarringsRTalon');
  Add(headpart, 'Model', True);
  SetElementEditValues(headPart, 'Model\MODL', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_Tiger.nif');
  Add(headpart, 'Parts', True);


  e := ElementByIndex(ElementByPath(headpart, 'Parts'), 0);
  SetElementEditValues(e, 'NAM0', 'Tri');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_Tiger.tri');
                            

  e := ElementAssign(ElementByPath(headpart, 'Parts'), HighInteger, nil, False);
  SetElementEditValues(e, 'NAM0', 'Chargen Morph');
  SetElementEditValues(e, 'NAM1', 'YAS/Feline/Earrings/Male/CatMaleEarringsRTalon_TigerChargen.tri');

end;
            
end.
