import bpy

skyrimGroups = 1

name_list = [
# old name - new name
('1H Axes on Back', '1H Axes on Back'),
('1H Swords on Back', '1H Swords on Back'),
('Aesthetic Bolt Quiver', 'Aesthetic Bolt Quiver'),
('AnimObjectA', 'AnimObjectA'),
('AnimObjectB', 'AnimObjectB'),
('AnimObject.L', 'AnimObjectL'),
('AnimObject.R', 'AnimObjectR'),
('Ankle Dagger Main', 'Ankle Dagger Main'),
('Ankle Dagger Offhand', 'Ankle Dagger Offhand'),
('BOLT', 'BOLT'),
('BOLTABQ', 'BOLTABQ'),
('BOLTChesko', 'BOLTChesko'),
('BOLTDefault', 'BOLTDefault'),
('BOLTLeftHipBolt', 'BOLTLeftHipBolt'),
('BOLTXP32', 'BOLTXP32'),
('BOLT_QUIVER', 'BOLT_QUIVER'),
('Back Hip Dagger', 'Back Hip Dagger'),
('Belly', 'Belly'),
('Better Bow', 'Better Bow'),
('Bolt Quiver', 'Bolt Quiver'),
('Breast', 'Breast'),
('Butt', 'Butt'),
('CME BOLT', 'CME BOLT'),
('CME BOLTABQ', 'CME BOLTABQ'),
('CME BOLTChesko', 'CME BOLTChesko'),
('CME BOLTDefault', 'CME BOLTDefault'),
('CME BOLTLeftHipBolt', 'CME BOLTLeftHipBolt'),
('CME BOLTXP32', 'CME BOLTXP32'),
('CME BOLT_QUIVER', 'CME BOLT_QUIVER'),
('CME Body', 'CME Body [Body]'),
('CME Camera3rd', 'CME Camera3rd [Cam3]'),
('CME Genitals01', 'CME Genitals01 [Gen01]'),
('CME Genitals02', 'CME Genitals02 [Gen02]'),
('CME Genitals03', 'CME Genitals03 [Gen03]'),
('CME Genitals04', 'CME Genitals04 [Gen04]'),
('CME Genitals05', 'CME Genitals05 [Gen05]'),
('CME GenitalsBase', 'CME GenitalsBase [GenBase]'),
('CME GenitalsScrotum', 'CME GenitalsScrotum [GenScrot]'),
('CME Breast.L', 'CME L Breast'),
('CME Calf.L', 'CME L Calf [LClf]'),
('CME Clavicle.L', 'CME L Clavicle [LClv]'),
('CME Finger00.L', 'CME L Finger00 [LF00]'),
('CME Finger01.L', 'CME L Finger01 [LF01]'),
('CME Finger10.L', 'CME L Finger10 [LF10]'),
('CME Finger11.L', 'CME L Finger11 [LF11]'),
('CME Finger20.L', 'CME L Finger20 [LF20]'),
('CME Finger21.L', 'CME L Finger21 [LF21]'),
('CME Finger30.L', 'CME L Finger30 [LF30]'),
('CME Finger31.L', 'CME L Finger31 [LF31]'),
('CME Finger40.L', 'CME L Finger40 [LF40]'),
('CME Finger41.L', 'CME L Finger41 [LF41]'),
('CME Foot.L', 'CME L Foot [Lft ]'),
('CME Forearm.L', 'CME L Forearm [LLar]'),
('CME Hand.L', 'CME L Hand [LHnd]'),
('CME Hip.L', 'CME L Hip'),
('CME Knee.L', 'CME L Knee [LKne]'),
('CME PreBreast.L', 'CME L PreBreast'),
('CME PreBreastRoot.L', 'CME L PreBreastRoot'),
('CME PreButt.L', 'CME L PreButt'),
('CME PreButt0.L', 'CME L PreButt0'),
('CME PreButtRoot.L', 'CME L PreButtRoot'),
('CME Shoulder.L', 'CME L Shoulder'),
('CME Thigh.L', 'CME L Thigh [LThg]'),
('CME Toe0.L', 'CME L Toe0 [LToe]'),
('CME UpperArm.L', 'CME L UpperArm [LUar]'),
('CME LBody', 'CME LBody [LBody]'),
('CME Neck', 'CME Neck [Neck]'),
('CME Pelvis', 'CME Pelvis [Pelv]'),
('CME QUIVERChesko', 'CME QUIVERChesko'),
('CME QUIVERDefault', 'CME QUIVERDefault'),
('CME QUIVERLeftHipBolt', 'CME QUIVERLeftHipBolt'),
('CME Breast.R', 'CME R Breast'),
('CME Calf.R', 'CME R Calf [RClf]'),
('CME Clavicle.R', 'CME R Clavicle [RClv]'),
('CME Finger00.R', 'CME R Finger00 [RF00]'),
('CME Finger01.R', 'CME R Finger01 [RF01]'),
('CME Finger10.R', 'CME R Finger10 [RF10]'),
('CME Finger11.R', 'CME R Finger11 [RF11]'),
('CME Finger20.R', 'CME R Finger20 [RF20]'),
('CME Finger21.R', 'CME R Finger21 [RF21]'),
('CME Finger30.R', 'CME R Finger30 [RF30]'),
('CME Finger31.R', 'CME R Finger31 [RF31]'),
('CME Finger40.R', 'CME R Finger40 [RF40]'),
('CME Finger41.R', 'CME R Finger41 [RF41]'),
('CME Foot.R', 'CME R Foot [Rft ]'),
('CME Forearm.R', 'CME R Forearm [RLar]'),
('CME Hand.R', 'CME R Hand [RHnd]'),
('CME Hip.R', 'CME R Hip'),
('CME Knee.R', 'CME R Knee [RKne]'),
('CME PreBreast.R', 'CME R PreBreast'),
('CME PreBreastRoot.R', 'CME R PreBreastRoot'),
('CME PreButt.R', 'CME R PreButt'),
('CME PreButt0.R', 'CME R PreButt0'),
('CME PreButtRoot.R', 'CME R PreButtRoot'),
('CME Shoulder.R', 'CME R Shoulder'),
('CME Thigh.R', 'CME R Thigh [RThg]'),
('CME Toe0.R', 'CME R Toe0 [RToe]'),
('CME UpperArm.R', 'CME R UpperArm [RUar]'),
('CME SchlongMagic', 'CME SchlongMagic'),
('CME ShieldBackDefault', 'CME ShieldBackDefault'),
('CME Spine', 'CME Spine [Spn0]'),
('CME Spine1', 'CME Spine1 [Spn1]'),
('CME Spine2', 'CME Spine2 [Spn2]'),
('CME Tail Thigh.L', 'CME Tail L Thigh [LThg]'),
('CME Tail Pelvis', 'CME Tail Pelvis [Pelv]'),
('CME Tail Thigh.R', 'CME Tail R Thigh [RThg]'),
('CME Tail Spine', 'CME Tail Spine [Spn0]'),
('CME Tail Spine1', 'CME Tail Spine1 [Spn1]'),
('CME TailBone01', 'CME TailBone01'),
('CME TailBone02', 'CME TailBone02'),
('CME TailBone03', 'CME TailBone03'),
('CME TailBone04', 'CME TailBone04'),
('CME UBody', 'CME UBody [UBody]'),
('CME WeaponAxeDefault', 'CME WeaponAxeDefault'),
('CME WeaponAxeDefault.L', 'CME WeaponAxeLeftDefault'),
('CME WeaponAxeOnBack.L', 'CME WeaponAxeLeftOnBack'),
('CME WeaponAxeReverse.L', 'CME WeaponAxeLeftReverse'),
('CME WeaponAxeOnBack', 'CME WeaponAxeOnBack'),
('CME WeaponAxeReverse', 'CME WeaponAxeReverse'),
('CME WeaponBackAxeMaceDefault', 'CME WeaponBackAxeMaceDefault'),
('CME WeaponBackAxeMaceFSM', 'CME WeaponBackAxeMaceFSM'),
('CME WeaponBackAxeMaceSWP', 'CME WeaponBackAxeMaceSWP'),
('CME WeaponBackDefault', 'CME WeaponBackDefault'),
('CME WeaponBackFSM', 'CME WeaponBackFSM'),
('CME WeaponBackSWP', 'CME WeaponBackSWP'),
('CME WeaponBowBetter', 'CME WeaponBowBetter'),
('CME WeaponBowChesko', 'CME WeaponBowChesko'),
('CME WeaponBowDefault', 'CME WeaponBowDefault'),
('CME WeaponBowFSM', 'CME WeaponBowFSM'),
('CME WeaponCrossBowChesko', 'CME WeaponCrossBowChesko'),
('CME WeaponCrossBowDefault', 'CME WeaponCrossBowDefault'),
('CME WeaponDaggerAnkle', 'CME WeaponDaggerAnkle'),
('CME WeaponDaggerBackHip', 'CME WeaponDaggerBackHip'),
('CME WeaponDaggerDefault', 'CME WeaponDaggerDefault'),
('CME WeaponDaggerAnkle.L', 'CME WeaponDaggerLeftAnkle'),
('CME WeaponDaggerBackHip.L', 'CME WeaponDaggerLeftBackHip'),
('CME WeaponDaggerDefault.L', 'CME WeaponDaggerLeftDefault'),
('CME WeaponMaceDefault', 'CME WeaponMaceDefault'),
('CME WeaponMaceDefault.L', 'CME WeaponMaceLeftDefault'),
('CME WeaponStaffDefault', 'CME WeaponStaffDefault'),
('CME WeaponStaffDefault.L', 'CME WeaponStaffLeftDefault'),
('CME WeaponSwordDefault', 'CME WeaponSwordDefault'),
('CME WeaponSwordFSM', 'CME WeaponSwordFSM'),
('CME WeaponSwordDefault.L', 'CME WeaponSwordLeftDefault'),
('CME WeaponSwordFSM.L', 'CME WeaponSwordLeftFSM'),
('CME WeaponSwordHip.L', 'CME WeaponSwordLeftHip'),
('CME WeaponSwordLeftHip.L', 'CME WeaponSwordLeftLeftHip'),
('CME WeaponSwordNMD.L', 'CME WeaponSwordLeftNMD'),
('CME WeaponSwordOnBack.L', 'CME WeaponSwordLeftOnBack'),
('CME WeaponSwordSWP.L', 'CME WeaponSwordLeftSWP'),
('CME WeaponSwordNMD', 'CME WeaponSwordNMD'),
('CME WeaponSwordOnBack', 'CME WeaponSwordOnBack'),
('CME WeaponSwordSWP', 'CME WeaponSwordSWP'),
('Camera Control', 'Camera Control'),
('Camera3rd', 'Camera3rd [Cam3]'),
('CharacterBumper', 'CharacterBumper'),
('Chesko Bow', 'Chesko Bow'),
('Chesko Quiver', 'Chesko Quiver'),
('Default Axe', 'Default Axe'),
('Default Bow and Quiver', 'Default Bow and Quiver'),
('Default Dagger', 'Default Dagger'),
('Default Mace', 'Default Mace'),
('Default ShieldBack', 'Default ShieldBack'),
('Default Staff', 'Default Staff'),
('Default Sword', 'Default Sword'),
('Default WeaponBack', 'Default WeaponBack'),
('Default WeaponBackAxeMace', 'Default WeaponBackAxeMace'),
('FSM Bow', 'FSM Bow'),
('FSM Sword', 'FSM Sword'),
('FSM WeaponBack', 'FSM WeaponBack'),
('FSM WeaponBackAxeMace', 'FSM WeaponBackAxeMace'),
('Genitals', 'Genitals'),
('GenitalsLag01', 'GenitalsLag01'),
('GenitalsLag02', 'GenitalsLag02'),
('GenitalsLag03', 'GenitalsLag03'),
('GenitalsLag04', 'GenitalsLag04'),
('GenitalsLag05', 'GenitalsLag05'),
('GenitalsLag06', 'GenitalsLag06'),
('GenitalsScrotumLag', 'GenitalsScrotumLag'),
('HDT Belly', 'HDT Belly'),
('HDT QUIVER', 'HDT QUIVER'),
('HDT ShieldBack', 'HDT ShieldBack'),
('HDT Tail', 'HDT Tail'),
('HDT TailBone01', 'HDT TailBone01'),
('HDT TailBone01.1', 'HDT TailBone01.1'),
('HDT TailBone01.2', 'HDT TailBone01.2'),
('HDT TailBone01.3', 'HDT TailBone01.3'),
('HDT TailBone02', 'HDT TailBone02'),
('HDT TailBone02.1', 'HDT TailBone02.1'),
('HDT TailBone02.2', 'HDT TailBone02.2'),
('HDT TailBone02.3', 'HDT TailBone02.3'),
('HDT TailBone03', 'HDT TailBone03'),
('HDT TailBone03.1', 'HDT TailBone03.1'),
('HDT TailBone03.2', 'HDT TailBone03.2'),
('HDT TailBone03.3', 'HDT TailBone03.3'),
('HDT TailBone04', 'HDT TailBone04'),
('HDT TailBone04.1', 'HDT TailBone04.1'),
('HDT TailBone04.2', 'HDT TailBone04.2'),
('HDT TailBone04.3', 'HDT TailBone04.3'),
('HDT TailBone05', 'HDT TailBone05'),
('HDT TailBone05.1', 'HDT TailBone05.1'),
('HDT TailBone05.2', 'HDT TailBone05.2'),
('HDT TailBone05.3', 'HDT TailBone05.3'),
('HDT TailBone06', 'HDT TailBone06'),
('HDT WeaponAxe', 'HDT WeaponAxe'),
('HDT WeaponAxe.L', 'HDT WeaponAxeLeft'),
('HDT WeaponBack', 'HDT WeaponBack'),
('HDT WeaponBow', 'HDT WeaponBow'),
('HDT WeaponDagger', 'HDT WeaponDagger'),
('HDT WeaponDagger.L', 'HDT WeaponDaggerLeft'),
('HDT WeaponMace', 'HDT WeaponMace'),
('HDT WeaponMace.L', 'HDT WeaponMaceLeft'),
('HDT WeaponStaff', 'HDT WeaponStaff'),
('HDT WeaponStaff.L', 'HDT WeaponStaffLeft'),
('HDT WeaponSword', 'HDT WeaponSword'),
('HDT WeaponSword.L', 'HDT WeaponSwordLeft'),
('HorseSpine2', 'HorseSpine2'),
('Left Hip Bolt Quiver', 'Left Hip Bolt Quiver'),
('Left Hip Swords', 'Left Hip Swords'),
('Wing1.L', 'LeftWing1'),
('Wing2.L', 'LeftWing2'),
('Wing3.L', 'LeftWing3'),
('Wing4.L', 'LeftWing4'),
('Wing5.L', 'LeftWing5'),
('MOV BOLT', 'MOV BOLT'),
('MOV BOLTABQ', 'MOV BOLTABQ'),
('MOV BOLTChesko', 'MOV BOLTChesko'),
('MOV BOLTDefault', 'MOV BOLTDefault'),
('MOV BOLTLeftHipBolt', 'MOV BOLTLeftHipBolt'),
('MOV BOLTXP32', 'MOV BOLTXP32'),
('MOV BOLT_QUIVER', 'MOV BOLT_QUIVER'),
('MOV QUIVERChesko', 'MOV QUIVERChesko'),
('MOV QUIVERDefault', 'MOV QUIVERDefault'),
('MOV QUIVERLeftHipBolt', 'MOV QUIVERLeftHipBolt'),
('MOV ShieldBackDefault', 'MOV ShieldBackDefault'),
('MOV WeaponAxeDefault', 'MOV WeaponAxeDefault'),
('MOV WeaponAxeDefault.L', 'MOV WeaponAxeLeftDefault'),
('MOV WeaponAxeOnBack.L', 'MOV WeaponAxeLeftOnBack'),
('MOV WeaponAxeReverse.L', 'MOV WeaponAxeLeftReverse'),
('MOV WeaponAxeOnBack', 'MOV WeaponAxeOnBack'),
('MOV WeaponAxeReverse', 'MOV WeaponAxeReverse'),
('MOV WeaponBackAxeMaceDefault', 'MOV WeaponBackAxeMaceDefault'),
('MOV WeaponBackAxeMaceFSM', 'MOV WeaponBackAxeMaceFSM'),
('MOV WeaponBackAxeMaceSWP', 'MOV WeaponBackAxeMaceSWP'),
('MOV WeaponBackDefault', 'MOV WeaponBackDefault'),
('MOV WeaponBackFSM', 'MOV WeaponBackFSM'),
('MOV WeaponBackSWP', 'MOV WeaponBackSWP'),
('MOV WeaponBowBetter', 'MOV WeaponBowBetter'),
('MOV WeaponBowChesko', 'MOV WeaponBowChesko'),
('MOV WeaponBowDefault', 'MOV WeaponBowDefault'),
('MOV WeaponBowFSM', 'MOV WeaponBowFSM'),
('MOV WeaponCrossBowChesko', 'MOV WeaponCrossBowChesko'),
('MOV WeaponCrossBowDefault', 'MOV WeaponCrossBowDefault'),
('MOV WeaponDaggerAnkle', 'MOV WeaponDaggerAnkle'),
('MOV WeaponDaggerBackHip', 'MOV WeaponDaggerBackHip'),
('MOV WeaponDaggerDefault', 'MOV WeaponDaggerDefault'),
('MOV WeaponDaggerAnkle.L', 'MOV WeaponDaggerLeftAnkle'),
('MOV WeaponDaggerBackHip.L', 'MOV WeaponDaggerLeftBackHip'),
('MOV WeaponDaggerDefault.L', 'MOV WeaponDaggerLeftDefault'),
('MOV WeaponMaceDefault', 'MOV WeaponMaceDefault'),
('MOV WeaponMaceDefault.L', 'MOV WeaponMaceLeftDefault'),
('MOV WeaponStaffDefault', 'MOV WeaponStaffDefault'),
('MOV WeaponStaffDefault.L', 'MOV WeaponStaffLeftDefault'),
('MOV WeaponSwordDefault', 'MOV WeaponSwordDefault'),
('MOV WeaponSwordFSM', 'MOV WeaponSwordFSM'),
('MOV WeaponSwordDefault.L', 'MOV WeaponSwordLeftDefault'),
('MOV WeaponSwordFSM.L', 'MOV WeaponSwordLeftFSM'),
('MOV WeaponSwordHip.L', 'MOV WeaponSwordLeftHip'),
('MOV WeaponSwordLeftHip.L', 'MOV WeaponSwordLeftLeftHip'),
('MOV WeaponSwordNMD.L', 'MOV WeaponSwordLeftNMD'),
('MOV WeaponSwordOnBack.L', 'MOV WeaponSwordLeftOnBack'),
('MOV WeaponSwordSWP.L', 'MOV WeaponSwordLeftSWP'),
('MOV WeaponSwordNMD', 'MOV WeaponSwordNMD'),
('MOV WeaponSwordOnBack', 'MOV WeaponSwordOnBack'),
('MOV WeaponSwordSWP', 'MOV WeaponSwordSWP'),
('MagicEffectsNode', 'MagicEffectsNode'),
('NMD Sword', 'NMD Sword'),
('NPC', 'NPC'),
('NPC Belly', 'NPC Belly'),
('NPC COM', 'NPC COM [COM ]'),
('NPC Genitals01', 'NPC Genitals01 [Gen01]'),
('NPC Genitals02', 'NPC Genitals02 [Gen02]'),
('NPC Genitals03', 'NPC Genitals03 [Gen03]'),
('NPC Genitals04', 'NPC Genitals04 [Gen04]'),
('NPC Genitals05', 'NPC Genitals05 [Gen05]'),
('NPC Genitals06', 'NPC Genitals06 [Gen06]'),
('NPC GenitalsBase', 'NPC GenitalsBase [GenBase]'),
('NPC GenitalsScrotum', 'NPC GenitalsScrotum [GenScrot]'),
('NPC Head MagicNode', 'NPC Head MagicNode [Hmag]'),
('NPC Head', 'NPC Head [Head]'),
('NPC Breast.L', 'NPC L Breast'),
('NPC Breast01.L', 'NPC L Breast01'),
('NPC Butt.L', 'NPC L Butt'),
('NPC Calf.L', 'NPC L Calf [LClf]'),
('NPC Clavicle.L', 'NPC L Clavicle [LClv]'),
('NPC Finger00.L', 'NPC L Finger00 [LF00]'),
('NPC Finger01.L', 'NPC L Finger01 [LF01]'),
('NPC Finger02.L', 'NPC L Finger02 [LF02]'),
('NPC Finger10.L', 'NPC L Finger10 [LF10]'),
('NPC Finger11.L', 'NPC L Finger11 [LF11]'),
('NPC Finger12.L', 'NPC L Finger12 [LF12]'),
('NPC Finger20.L', 'NPC L Finger20 [LF20]'),
('NPC Finger21.L', 'NPC L Finger21 [LF21]'),
('NPC Finger22.L', 'NPC L Finger22 [LF22]'),
('NPC Finger30.L', 'NPC L Finger30 [LF30]'),
('NPC Finger31.L', 'NPC L Finger31 [LF31]'),
('NPC Finger32.L', 'NPC L Finger32 [LF32]'),
('NPC Finger40.L', 'NPC L Finger40 [LF40]'),
('NPC Finger41.L', 'NPC L Finger41 [LF41]'),
('NPC Finger42.L', 'NPC L Finger42 [LF42]'),
('NPC Foot.L', 'NPC L Foot [Lft ]'),
('NPC Forearm.L', 'NPC L Forearm [LLar]'),
('NPC ForearmTwist1.L', 'NPC L ForearmTwist1 [LLt1]'),
('NPC ForearmTwist2.L', 'NPC L ForearmTwist2 [LLt2]'),
('NPC FrontThigh.L', 'NPC L FrontThigh'),
('NPC GenitalsScrotum.L', 'NPC L GenitalsScrotum [LGenScrot]'),
('NPC Hand.L', 'NPC L Hand [LHnd]'),
('NPC Joint 1.L', 'NPC L Joint 1 [Lft ]'),
('NPC Joint 2.L', 'NPC L Joint 2 [Lft ]'),
('NPC Joint 3.L', 'NPC L Joint 3 [Lft ]'),
('NPC Joint 4.L', 'NPC L Joint 4 [Lft ]'),
('NPC Joint 5.L', 'NPC L Joint 5 [Lft ]'),
('NPC MagicNode.L', 'NPC L MagicNode [LMag]'),
('NPC Pauldron.L', 'NPC L Pauldron'),
('NPC PreBreast.L', 'NPC L PreBreast'),
('NPC PreButt.L', 'NPC L PreButt'),
('NPC PreButt0.L', 'NPC L PreButt0'),
('NPC PreFrontThigh.L', 'NPC L PreFrontThigh'),
('NPC PreRearCalf.L', 'NPC L PreRearCalf'),
('NPC PreRearThigh.L', 'NPC L PreRearThigh'),
('NPC RearCalf.L', 'NPC L RearCalf [LrClf]'),
('NPC RearThigh.L', 'NPC L RearThigh'),
('NPC ScaleBreast.L', 'NPC L ScaleBreast'),
('NPC ScaleButt.L', 'NPC L ScaleButt'),
('NPC Thigh.L', 'NPC L Thigh [LThg]'),
('NPC Toe 1.L', 'NPC L Toe 1 [Lft ]'),
('NPC Toe 2.L', 'NPC L Toe 2 [Lft ]'),
('NPC Toe 3.L', 'NPC L Toe 3 [Lft ]'),
('NPC Toe 4.L', 'NPC L Toe 4 [Lft ]'),
('NPC Toe 5.L', 'NPC L Toe 5 [Lft ]'),
('NPC Toe0.L', 'NPC L Toe0 [LToe]'),
('NPC UpperArm.L', 'NPC L UpperArm [LUar]'),
('NPC UpperarmTwist1.L', 'NPC L UpperarmTwist1 [LUt1]'),
('NPC UpperarmTwist2.L', 'NPC L UpperarmTwist2 [LUt2]'),
('NPC Neck', 'NPC Neck [Neck]'),
('NPC Pelvis', 'NPC Pelvis [Pelv]'),
('NPC Breast.R', 'NPC R Breast'),
('NPC Breast01.R', 'NPC R Breast01'),
('NPC Butt.R', 'NPC R Butt'),
('NPC Calf.R', 'NPC R Calf [RClf]'),
('NPC Clavicle.R', 'NPC R Clavicle [RClv]'),
('NPC Finger00.R', 'NPC R Finger00 [RF00]'),
('NPC Finger01.R', 'NPC R Finger01 [RF01]'),
('NPC Finger02.R', 'NPC R Finger02 [RF02]'),
('NPC Finger10.R', 'NPC R Finger10 [RF10]'),
('NPC Finger11.R', 'NPC R Finger11 [RF11]'),
('NPC Finger12.R', 'NPC R Finger12 [RF12]'),
('NPC Finger20.R', 'NPC R Finger20 [RF20]'),
('NPC Finger21.R', 'NPC R Finger21 [RF21]'),
('NPC Finger22.R', 'NPC R Finger22 [RF22]'),
('NPC Finger30.R', 'NPC R Finger30 [RF30]'),
('NPC Finger31.R', 'NPC R Finger31 [RF31]'),
('NPC Finger32.R', 'NPC R Finger32 [RF32]'),
('NPC Finger40.R', 'NPC R Finger40 [RF40]'),
('NPC Finger41.R', 'NPC R Finger41 [RF41]'),
('NPC Finger42.R', 'NPC R Finger42 [RF42]'),
('NPC Foot.R', 'NPC R Foot [Rft ]'),
('NPC Forearm.R', 'NPC R Forearm [RLar]'),
('NPC ForearmTwist1.R', 'NPC R ForearmTwist1 [RLt1]'),
('NPC ForearmTwist2.R', 'NPC R ForearmTwist2 [RLt2]'),
('NPC FrontThigh.R', 'NPC R FrontThigh'),
('NPC GenitalsScrotum.R', 'NPC R GenitalsScrotum [RGenScrot]'),
('NPC Hand.R', 'NPC R Hand [RHnd]'),
('NPC Joint 1.R', 'NPC R Joint 1 [Rft ]'),
('NPC Joint 2.R', 'NPC R Joint 2 [Rft ]'),
('NPC Joint 3.R', 'NPC R Joint 3 [Rft ]'),
('NPC Joint 4.R', 'NPC R Joint 4 [Rft ]'),
('NPC Joint 5.R', 'NPC R Joint 5 [Rft ]'),
('NPC MagicNode.R', 'NPC R MagicNode [RMag]'),
('NPC Pauldron.R', 'NPC R Pauldron'),
('NPC PreBreast.R', 'NPC R PreBreast'),
('NPC PreButt.R', 'NPC R PreButt'),
('NPC PreButt0.R', 'NPC R PreButt0'),
('NPC PreFrontThigh.R', 'NPC R PreFrontThigh'),
('NPC PreRearCalf.R', 'NPC R PreRearCalf'),
('NPC PreRearThigh.R', 'NPC R PreRearThigh'),
('NPC RearCalf.R', 'NPC R RearCalf [RrClf]'),
('NPC RearThigh.R', 'NPC R RearThigh'),
('NPC ScaleBreast.R', 'NPC R ScaleBreast'),
('NPC ScaleButt.R', 'NPC R ScaleButt'),
('NPC Thigh.R', 'NPC R Thigh [RThg]'),
('NPC Toe 1.R', 'NPC R Toe 1 [Rft ]'),
('NPC Toe 2.R', 'NPC R Toe 2 [Rft ]'),
('NPC Toe 3.R', 'NPC R Toe 3 [Rft ]'),
('NPC Toe 4.R', 'NPC R Toe 4 [Rft ]'),
('NPC Toe 5.R', 'NPC R Toe 5 [Rft ]'),
('NPC Toe0.R', 'NPC R Toe0 [RToe]'),
('NPC UpperArm.R', 'NPC R UpperArm [RUar]'),
('NPC UpperarmTwist1.R', 'NPC R UpperarmTwist1 [RUt1]'),
('NPC UpperarmTwist2.R', 'NPC R UpperarmTwist2 [RUt2]'),
('NPC Root', 'NPC Root [Root]'),
('NPC Spine', 'NPC Spine [Spn0]'),
('NPC Spine1', 'NPC Spine1 [Spn1]'),
('NPC Spine2', 'NPC Spine2 [Spn2]'),
('NPC Tail Thigh.L', 'NPC Tail L Thigh [LThg]'),
('NPC Tail Thigh.R', 'NPC Tail R Thigh [RThg]'),
('NPC Tail Spine', 'NPC Tail Spine [Spn0]'),
('NPC TailBone01', 'NPC TailBone01'),
('NPC TailBone02', 'NPC TailBone02'),
('NPC TailBone03', 'NPC TailBone03'),
('NPC TailBone04', 'NPC TailBone04'),
('NPC TailBone05', 'NPC TailBone05'),
('NPC TailBone06', 'NPC TailBone06'),
('NPC TailBone07', 'NPC TailBone07'),
('NPC TailBone08', 'NPC TailBone08'),
('NPCEyeBone', 'NPCEyeBone'),
('POS Tail', 'POS Tail'),
('POS TailBone01', 'POS TailBone01'),
('POS TailBone02', 'POS TailBone02'),
('POS TailBone03', 'POS TailBone03'),
('POS TailBone04', 'POS TailBone04'),
('POS TailBone05', 'POS TailBone05'),
('POS TailBone06', 'POS TailBone06'),
('POS TailBone07', 'POS TailBone07'),
('POS TailBone08', 'POS TailBone08'),
('POS TailSpine', 'POS TailSpine'),
('POS TailSpine1', 'POS TailSpine1'),
('PreSHIELD', 'PreSHIELD'),
('PreWEAPON', 'PreWEAPON'),
('QUIVER', 'QUIVER'),
('QUIVERChesko', 'QUIVERChesko'),
('QUIVERLeftHipBolt', 'QUIVERLeftHipBolt'),
('Reverse Axe', 'Reverse Axe'),
('Wing1.R', 'RightWing1'),
('Wing2.R', 'RightWing2'),
('Wing3.R', 'RightWing3'),
('Wing4.R', 'RightWing4'),
('Wing5.R', 'RightWing5'),
('SHIELD', 'SHIELD'),
('SWP Swords on Back', 'SWP Swords on Back'),
('SWP WeaponBack', 'SWP WeaponBack'),
('SWP WeaponBackAxeMace', 'SWP WeaponBackAxeMace'),
('Schlong', 'Schlong'),
('SchlongMagic', 'SchlongMagic'),
('ShieldBack', 'ShieldBack'),
('Skirt', 'Skirt'),
('SkirtBBone01', 'SkirtBBone01'),
('SkirtBBone02', 'SkirtBBone02'),
('SkirtBBone03', 'SkirtBBone03'),
('SkirtFBone01', 'SkirtFBone01'),
('SkirtFBone02', 'SkirtFBone02'),
('SkirtFBone03', 'SkirtFBone03'),
('SkirtBone01.L', 'SkirtLBone01'),
('SkirtBone02.L', 'SkirtLBone02'),
('SkirtBone03.L', 'SkirtLBone03'),
('SkirtBone01.R', 'SkirtRBone01'),
('SkirtBone02.R', 'SkirtRBone02'),
('SkirtBone03.R', 'SkirtRBone03'),
('Tail', 'Tail'),
('Tail Main', 'Tail Main'),
('TailBone01', 'TailBone01'),
('TailBone02', 'TailBone02'),
('TailBone03', 'TailBone03'),
('TailBone04', 'TailBone04'),
('TailBone05', 'TailBone05'),
('Tails', 'Tails'),
('VampireLord Wings', 'VampireLord Wings'),
('WEAPON', 'WEAPON'),
('Weapon Calf.L', 'Weapon L Calf'),
('Weapon Pelvis', 'Weapon Pelvis'),
('Weapon Calf.R', 'Weapon R Calf'),
('Weapon Spine1', 'Weapon Spine1'),
('Weapon Spine2', 'Weapon Spine2'),
('WeaponAxe', 'WeaponAxe'),
('WeaponAxe.L', 'WeaponAxeLeft'),
('WeaponAxeOnBack.L', 'WeaponAxeLeftOnBack'),
('WeaponAxeReverse.L', 'WeaponAxeLeftReverse'),
('WeaponAxeOnBack', 'WeaponAxeOnBack'),
('WeaponAxeReverse', 'WeaponAxeReverse'),
('WeaponBack', 'WeaponBack'),
('WeaponBackAxeMace', 'WeaponBackAxeMace'),
('WeaponBackAxeMaceFSM', 'WeaponBackAxeMaceFSM'),
('WeaponBackAxeMaceSWP', 'WeaponBackAxeMaceSWP'),
('WeaponBackFSM', 'WeaponBackFSM'),
('WeaponBackSWP', 'WeaponBackSWP'),
('WeaponBow', 'WeaponBow'),
('WeaponBowBetter', 'WeaponBowBetter'),
('WeaponBowChesko', 'WeaponBowChesko'),
('WeaponBowFSM', 'WeaponBowFSM'),
('WeaponCrossBow', 'WeaponCrossBow'),
('WeaponCrossBowChesko', 'WeaponCrossBowChesko'),
('WeaponDagger', 'WeaponDagger'),
('WeaponDaggerAnkle', 'WeaponDaggerAnkle'),
('WeaponDaggerBackHip', 'WeaponDaggerBackHip'),
('WeaponDagger.L', 'WeaponDaggerLeft'),
('WeaponDaggerAnkle.L', 'WeaponDaggerLeftAnkle'),
('WeaponDaggerBackHip.L', 'WeaponDaggerLeftBackHip'),
('WeaponMace', 'WeaponMace'),
('WeaponMace.L', 'WeaponMaceLeft'),
('WeaponStaff', 'WeaponStaff'),
('WeaponStaff.L', 'WeaponStaffLeft'),
('WeaponSword', 'WeaponSword'),
('WeaponSwordFSM', 'WeaponSwordFSM'),
('WeaponSword.L', 'WeaponSwordLeft'),
('WeaponSwordFSM.L', 'WeaponSwordLeftFSM'),
('WeaponSwordHip.L', 'WeaponSwordLeftHip'),
('WeaponSwordLeftHip.L', 'WeaponSwordLeftLeftHip'),
('WeaponSwordNMD.L', 'WeaponSwordLeftNMD'),
('WeaponSwordOnBack.L', 'WeaponSwordLeftOnBack'),
('WeaponSwordSWP.L', 'WeaponSwordLeftSWP'),
('WeaponSwordNMD', 'WeaponSwordNMD'),
('WeaponSwordOnBack', 'WeaponSwordOnBack'),
('WeaponSwordSWP', 'WeaponSwordSWP'),
]

for obj in bpy.context.selected_objects:
    v_groups = obj.vertex_groups
    for old_name, new_name in name_list:
        if old_name in v_groups:
            v_groups[old_name].name = new_name
        elif new_name in v_groups:
            v_groups[new_name].name = old_name
    print('done')